export enum DefaultJSEvents {
    Load =  "load",
    Mouseenter = "mouseenter",
    Mouseleave = "mouseleave",
    Mousedown = "mousedown",
    Mousemove = "mousemove",
    Mouseup = "mouseup",
    Mouseover = "mouseover",
    Keyup = "keyup",
    Keydown = "keydown",
    Blur = "blur",
    SelectStart = "selectstart",
    SelectionChange = "selectionchange",
    Click = "click",
    Focusin = "focusin",
    Focusout = "focusout",
    DOMContentLoaded = "DOMContentLoaded",
    Input = "input",
    BblClick = "dblclick"
}