export enum Icons {
    Link = "icon-material-link",
    Bold = "icon-wordpress-bold",
    Italic = "icon-material-italic",
    Underline = "icon-material-underline",
    InlineCode = "icon-material-code-inline",
    StrikeThrough = "icon-wordpress-strike-through",
    Plus = "icon-plus",
    ColumnRight = "icon-material-column-right",
    ColumnLeft = "icon-material-column-left",
    RowAbove = "icon-material-row-above",
    RowBelow = "icon-material-row-below",
    deleteSweep = "icon-material-delete-sweep",
    Trash = "icon-material-trash",
    CloseCircle = "icon-ionic-close-circle",
    Empty = "Empty",
    Callout = "icon-material-callout",
    Image = "icon-material-image",
    Image2 = "icon-bootstrap-image",
    Video = "icon-material-video",
    JustifyStart =  "icon-material-justify-start",
    JustifyCenter = "icon-material-justify-center",
    JustifyEnd = "icon-material-justify-end",
    Duplicate = "icon-material-duplicate",
    Spotify = "icon-bootstrap-spotify",
    GitHub = "icon-bootstrap-github",
    GitLab = "icon-bootstrap-gitlab",
    CodePen = "icon-codepen",
    YouTube = "icon-bootstrap-youtube"

}